
name: Docker Image CI (build, tag, push)

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Get tag from commit
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        # Optionally strip `v` prefix
        strip_v: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      - run: docker build . --file Dockerfile.prod --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 
      - run: dockerd tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} 
      # run: echo '::set-output name=SELECTED_COLOR::green'

    - name: Push to GHRC.IO
      # run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

